apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummyobjects.khmarochos.melnyk.host
spec:
  group: khmarochos.melnyk.host
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: dummyobjects
    singular: dummyobject
    kind: DummyObject
    shortNames:
      - dobj
