apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dummyobjects-manager
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
rules:
- apiGroups:
  - khmarochos.melnyk.host
  resources:
  - dummyobjects
  verbs:
  - '*'
