{{- if .Values.dockerRegistryCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.imagePullSecretName" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "demo-app.imagePullSecret" . }}
{{- end }}
